"""Import an ordinary Blender Mesh as a Halo 2.x native OBJ primitive.

The native Halo loader intentionally accepts a small OBJ subset.  This bridge
therefore writes its own deterministic OBJ instead of relying on Blender's
general exporter: evaluated geometry is reduced to textured triangles, all
coordinates are converted back to Minecraft space, and unsupported OBJ/MTL
features never enter the resource pack.
"""

from __future__ import annotations

from array import array
from dataclasses import dataclass
import hashlib
import math
from pathlib import Path
import re
import tempfile

try:
    import bpy
    from mathutils import Matrix
except ImportError:  # pragma: no cover - Blender-only integration
    bpy = None
    Matrix = None

from .geometry import blender_to_mc
from .materials import copy_texture_with_sidecars, split_resource_id
from .mesh_conversion import DirectUVUnsupported, _active_output, _direct_uv_material
from .obj_mesh import copy_obj_resource, parse_obj


@dataclass
class SceneMeshImportResult:
    model_id: str
    texture_id: str | None
    triangle_count: int
    skipped_degenerate: int
    generated_texture: bool
    warnings: list[str]


def _safe_component(value: str, fallback: str = "model") -> str:
    result = re.sub(r"[^a-z0-9._-]+", "_", str(value or "").strip().lower()).strip("._-")
    return result or fallback


def _number(value: float) -> str:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError("网格包含非有限坐标或 UV")
    if abs(value) < 5.0e-13:
        value = 0.0
    return format(value, ".9g")


def obj_text_from_mesh(mesh, name: str = "model") -> tuple[str, int, int]:
    """Serialize one Blender Mesh to Halo's textured-triangle OBJ subset."""

    if mesh is None or not mesh.vertices or not mesh.polygons:
        raise ValueError("源网格没有可导出的面")
    uv_layer = mesh.uv_layers.active if mesh.uv_layers else None
    if uv_layer is None:
        raise ValueError("Halo OBJ 的每个顶点都必须有 UV；请生成 UV 或使用烘焙模式")
    mesh.calc_loop_triangles()
    position_indices: dict[int, int] = {}
    uv_indices: dict[tuple[float, float], int] = {}
    positions: list[tuple[float, float, float]] = []
    uvs: list[tuple[float, float]] = []
    faces: list[tuple[tuple[int, int], tuple[int, int], tuple[int, int]]] = []
    skipped = 0
    for triangle in mesh.loop_triangles:
        points = [mesh.vertices[index].co for index in triangle.vertices]
        if (points[1] - points[0]).cross(points[2] - points[0]).length_squared <= 1.0e-20:
            skipped += 1
            continue
        corners = []
        for vertex_index, loop_index in zip(triangle.vertices, triangle.loops):
            if vertex_index not in position_indices:
                position_indices[vertex_index] = len(positions) + 1
                positions.append(tuple(blender_to_mc(mesh.vertices[vertex_index].co)))
            uv = tuple(float(value) for value in uv_layer.data[loop_index].uv)
            # Blender UV values may legally leave 0..1.  Halo uses the same
            # normalized coordinates and controls wrapping in the shader.
            key = (uv[0], uv[1])
            if key not in uv_indices:
                uv_indices[key] = len(uvs) + 1
                uvs.append(key)
            corners.append((position_indices[vertex_index], uv_indices[key]))
        faces.append(tuple(corners))
    if not faces:
        raise ValueError("源网格只包含退化面")
    lines = ["# Generated by Halo Pack Editor", f"o {_safe_component(name)}"]
    lines.extend("v " + " ".join(_number(value) for value in position) for position in positions)
    lines.extend("vt " + " ".join(_number(value) for value in uv) for uv in uvs)
    lines.extend("f " + " ".join(f"{position}/{uv}" for position, uv in face) for face in faces)
    text = "\n".join(lines) + "\n"
    # Treat Halo's own parser as the final contract, including element and
    # text-size guards.  This catches future writer regressions before files
    # are copied into the editable pack.
    parse_obj(text, f"generated:{_safe_component(name)}.obj")
    return text, len(faces), skipped


def _restore_selection(context, selected, active, mode):
    try:
        if context.object is not None and context.object.mode != "OBJECT":
            bpy.ops.object.mode_set(mode="OBJECT")
    except RuntimeError:
        pass
    for obj in list(context.selected_objects):
        obj.select_set(False)
    for obj in selected:
        if obj.name in bpy.data.objects:
            obj.select_set(True)
    if active is not None and active.name in bpy.data.objects:
        context.view_layer.objects.active = active
        if mode and mode != "OBJECT":
            try:
                bpy.ops.object.mode_set(mode=mode)
            except RuntimeError:
                pass


def _smart_uv(context, obj, island_margin: float) -> str:
    """Create a dedicated bake UV without changing material sampling UVs."""

    source_uv = obj.data.uv_layers.active if obj.data.uv_layers else None
    source_uv_name = source_uv.name if source_uv is not None else ""
    bake_uv = obj.data.uv_layers.new(name="Halo Bake UV")
    bake_uv_name = bake_uv.name
    obj.data.uv_layers.active_index = len(obj.data.uv_layers) - 1
    bake_uv.active_render = True
    previous_selected = list(context.selected_objects)
    previous_active = context.view_layer.objects.active
    previous_mode = getattr(previous_active, "mode", "OBJECT") if previous_active else "OBJECT"
    try:
        if context.object is not None and context.object.mode != "OBJECT":
            bpy.ops.object.mode_set(mode="OBJECT")
        for selected in context.selected_objects:
            selected.select_set(False)
        obj.select_set(True)
        context.view_layer.objects.active = obj
        bpy.ops.object.mode_set(mode="EDIT")
        bpy.ops.mesh.select_all(action="SELECT")
        bpy.ops.uv.smart_project(island_margin=max(0.0, min(1.0, float(island_margin))))
        bpy.ops.object.mode_set(mode="OBJECT")
        bake_uv = obj.data.uv_layers.get(bake_uv_name)
        if bake_uv is None:
            raise RuntimeError("Smart UV 未生成有效 UV 层")
        obj.data.update()
        # ShaderNodeTexCoord.UV samples the render-active layer, while the
        # bake operator below writes to its explicit uv_layer argument. Keep
        # the old authored UV render-active so image materials do not suddenly
        # sample through the new atlas (the former cause of scrambled bakes).
        source_uv = obj.data.uv_layers.get(source_uv_name) if source_uv_name else None
        if source_uv is not None:
            source_uv.active_render = True
        else:
            bake_uv.active_render = True
        return bake_uv_name
    finally:
        _restore_selection(context, previous_selected, previous_active, previous_mode)


def _dummy_uv(mesh):
    layer = mesh.uv_layers.new(name="Halo Generated UV")
    for loop in layer.data:
        loop.uv = (0.0, 0.0)
    mesh.uv_layers.active = layer


def _upstream_image_nodes(material):
    if material is None or not material.use_nodes or material.node_tree is None:
        return []
    output = _active_output(material.node_tree.nodes)
    if output is None:
        return []
    found = []
    visited = set()
    stack = [link.from_node for socket in output.inputs for link in socket.links]
    while stack:
        node = stack.pop()
        pointer = int(node.as_pointer())
        if pointer in visited:
            continue
        visited.add(pointer)
        if node.bl_idname == "ShaderNodeTexImage" and node.image is not None:
            found.append(node)
        stack.extend(link.from_node for socket in node.inputs for link in socket.links)
    return found


def _image_node_uv(node, mesh):
    vector = node.inputs.get("Vector")
    if vector is None or not vector.is_linked:
        return mesh.uv_layers.active.name if mesh.uv_layers.active else ""
    link = vector.links[0]
    source = link.from_node
    if source.bl_idname == "ShaderNodeUVMap" and link.from_socket.name == "UV":
        return str(source.uv_map or "")
    if source.bl_idname == "ShaderNodeTexCoord" and link.from_socket.name == "UV":
        return mesh.uv_layers.active.name if mesh.uv_layers.active else ""
    raise DirectUVUnsupported("图像坐标包含 Mapping、Generated 或其他无法写入 OBJ UV 的变换")


def _direct_image(obj, mesh):
    if mesh.uv_layers.active is None:
        raise DirectUVUnsupported("源 Mesh 没有 UV")
    by_material = {}
    for polygon in mesh.polygons:
        by_material.setdefault(int(polygon.material_index), []).append(polygon)
    try:
        configs = [_direct_uv_material(obj, polygons, mesh) for polygons in by_material.values()]
    except DirectUVUnsupported as strict_error:
        # Imported FBX/glTF/VRM materials often put one base image behind Mix
        # nodes even though the Halo-compatible resource is still unambiguous.
        # Accept that single-image case, but never guess among base/normal/mask
        # images: native Halo Mesh has only one base texture slot.
        images = {}
        uv_names = set()
        for material_index in by_material:
            material = obj.material_slots[material_index].material if material_index < len(obj.material_slots) else None
            nodes = _upstream_image_nodes(material)
            if not nodes:
                raise strict_error
            for node in nodes:
                image = node.image
                if image.source in {"TILED", "SEQUENCE", "MOVIE"} or node.projection != "FLAT":
                    raise DirectUVUnsupported("唯一图像使用了 UDIM/序列/视频或非 Flat 投影")
                images[int(image.as_pointer())] = image
                uv_names.add(_image_node_uv(node, mesh))
        if len(images) != 1:
            raise DirectUVUnsupported(
                f"有效材质图包含 {len(images)} 张图像，而 Halo Mesh 只有一个 texture；请用 Cycles 烘焙合并"
            )
        if len(uv_names) != 1 or not next(iter(uv_names), ""):
            raise DirectUVUnsupported("有效材质图使用了不同或缺失的 UV Map")
        uv_name = next(iter(uv_names))
        if mesh.uv_layers.get(uv_name) is None:
            raise DirectUVUnsupported(f"材质引用的 UV Map 不存在：{uv_name}")
        mesh.uv_layers.active = mesh.uv_layers.get(uv_name)
        return next(iter(images.values())), ["已从 Mix/复杂材质图提取唯一图像；节点颜色、明暗和透明运算不会写入 Halo"]
    if not configs or configs[0]["image"] is None:
        raise DirectUVUnsupported("材质没有直接连接到 Surface 的 Image Texture")
    image = configs[0]["image"]
    uv_name = configs[0]["uv_layer"]
    for config in configs:
        if config["image"] != image:
            raise DirectUVUnsupported("多个材质没有使用同一张主纹理")
        if config["uv_layer"] != uv_name:
            raise DirectUVUnsupported("多个材质使用了不同的 UV Map")
        if abs(float(config["strength"]) - 1.0) > 1.0e-6:
            raise DirectUVUnsupported("材质包含无法写入 Halo 纹理的强度倍率")
        if abs(float(config["alpha"]) - 1.0) > 1.0e-6:
            raise DirectUVUnsupported("材质包含无法写入 Halo 纹理的 Alpha 倍率")
    mesh.uv_layers.active = mesh.uv_layers.get(uv_name)
    return image, []


def _image_digest(image) -> str:
    width, height = int(image.size[0]), int(image.size[1])
    if width <= 0 or height <= 0:
        raise ValueError("源图像没有可读取的像素")
    pixels = array("f", [0.0]) * (width * height * 4)
    image.pixels.foreach_get(pixels)
    digest = hashlib.sha256()
    digest.update(f"{width}x{height}:{image.colorspace_settings.name}".encode("utf-8"))
    digest.update(pixels.tobytes())
    return digest.hexdigest()


def _generated_texture_id(
    pack_root: str,
    namespace: str,
    stem: str,
    digest: str | None = None,
    *,
    consider_files: bool = True,
):
    requested = f"{namespace}:textures/halo/{_safe_component(stem, 'texture')}.png"
    namespace_root = Path(pack_root).resolve() / "assets" / namespace
    namespace_root.mkdir(parents=True, exist_ok=True)
    base_relative = split_resource_id(requested)[1]
    base = Path(base_relative)
    index = 0
    while True:
        relative = base if index == 0 else base.with_name(f"{base.stem}_{index}{base.suffix}")
        candidate = f"{namespace}:{relative.as_posix()}"
        for image in bpy.data.images:
            if image.get("halo_texture_id") != candidate or image.get("halo_missing_texture"):
                continue
            if digest and image.get("halo_content_sha256") == digest:
                return candidate, image
            break
        else:
            if not consider_files or not (namespace_root / relative).exists():
                return candidate, None
        index += 1


def _copy_generated_image(image, texture_id: str, digest: str):
    copied = image.copy()
    copied.name = f"Halo Scene Mesh {Path(split_resource_id(texture_id)[1]).name}"
    copied["halo_generated_texture"] = True
    copied["halo_texture_id"] = texture_id
    copied["halo_content_sha256"] = digest
    copied.pop("halo_missing_texture", None)
    copied.pop("halo_source_path", None)
    copied.pack()
    copied.filepath_raw = ""
    return copied


def _import_direct_texture(image, pack_root: str, namespace: str, stem: str):
    digest = _image_digest(image)
    source = Path(bpy.path.abspath(str(image.filepath or ""))).resolve() if image.filepath else None
    # Existing disk files are compared by copy_texture_with_sidecars so an
    # identical PNG family is reused. In-memory generated images still need
    # to reserve their IDs before that disk-level comparison.
    texture_id, existing = _generated_texture_id(
        pack_root,
        namespace,
        stem,
        digest,
        consider_files=not (source is not None and source.is_file() and source.suffix.lower() == ".png"),
    )
    if existing is not None:
        return texture_id, False
    if source is not None and source.is_file() and source.suffix.lower() == ".png":
        copied = copy_texture_with_sidecars(str(source), pack_root, texture_id)
        actual = Path(copied[0]).resolve()
        assets = Path(pack_root).resolve() / "assets" / namespace
        return f"{namespace}:{actual.relative_to(assets).as_posix()}", False
    _copy_generated_image(image, texture_id, digest)
    return texture_id, True


def _copy_materials(mesh):
    originals = list(mesh.materials)
    materials = []
    mesh.materials.clear()
    if not originals:
        material = bpy.data.materials.new("Halo Scene Mesh Default")
        material.use_nodes = True
        materials.append(material)
        mesh.materials.append(material)
        return materials
    for original in originals:
        material = original.copy() if original is not None else bpy.data.materials.new("Halo Scene Mesh Default")
        material.use_nodes = True
        materials.append(material)
        mesh.materials.append(material)
    return materials


def _bake_texture(
    context,
    obj,
    resolution: int,
    margin: int,
    bake_mode: str,
    texture_id: str,
    bake_uv_name: str,
):
    resolution = max(16, min(8192, int(resolution)))
    margin = max(0, min(64, int(margin)))
    materials = _copy_materials(obj.data)
    color = bpy.data.images.new("Halo Scene Mesh Bake", width=resolution, height=resolution, alpha=True)
    color.generated_color = (0.0, 0.0, 0.0, 0.0)
    alpha = bpy.data.images.new("Halo Scene Mesh Bake Alpha", width=resolution, height=resolution, alpha=True)
    alpha.generated_color = (1.0, 1.0, 1.0, 1.0)
    original_surfaces = []
    target_nodes = []
    warnings = []
    for material in materials:
        nodes = material.node_tree.nodes
        output = _active_output(nodes)
        if output is None:
            output = nodes.new("ShaderNodeOutputMaterial")
        source = output.inputs["Surface"].links[0].from_node if output.inputs["Surface"].is_linked else None
        original_surfaces.append((material, output, source))
        target = nodes.new("ShaderNodeTexImage")
        target.name = "Halo Scene Mesh Bake Target"
        target.image = color
        for node in nodes:
            node.select = False
        target.select = True
        nodes.active = target
        target_nodes.append(target)

    selected_mode = str(bake_mode or "AUTO").upper()
    surface_types = {source.bl_idname if source is not None else "" for _material, _output, source in original_surfaces}
    if selected_mode == "AUTO":
        if surface_types <= {"ShaderNodeBsdfPrincipled"}:
            selected_mode = "DIFFUSE"
        elif surface_types <= {"ShaderNodeEmission"}:
            selected_mode = "EMIT"
        else:
            selected_mode = "COMBINED"

    previous_engine = context.scene.render.engine
    previous_selected = list(context.selected_objects)
    previous_active = context.view_layer.objects.active
    previous_mode = getattr(previous_active, "mode", "OBJECT") if previous_active else "OBJECT"
    bake_path = None
    success = False
    try:
        if context.object is not None and context.object.mode != "OBJECT":
            bpy.ops.object.mode_set(mode="OBJECT")
        for selected in context.selected_objects:
            selected.select_set(False)
        obj.select_set(True)
        context.view_layer.objects.active = obj
        context.scene.render.engine = "CYCLES"
        arguments = dict(margin=margin, use_clear=True, uv_layer=bake_uv_name)
        if selected_mode == "DIFFUSE":
            bpy.ops.object.bake(type="DIFFUSE", pass_filter={"COLOR"}, **arguments)
        else:
            bpy.ops.object.bake(type=selected_mode, **arguments)

        for target in target_nodes:
            target.image = alpha
        for material, output, source in original_surfaces:
            nodes, links = material.node_tree.nodes, material.node_tree.links
            emission = nodes.new("ShaderNodeEmission")
            emission.inputs["Strength"].default_value = 1.0
            alpha_socket = source.inputs.get("Alpha") if source is not None and source.bl_idname == "ShaderNodeBsdfPrincipled" else None
            if alpha_socket is not None and alpha_socket.is_linked:
                links.new(alpha_socket.links[0].from_socket, emission.inputs["Color"])
            else:
                value = float(alpha_socket.default_value) if alpha_socket is not None else 1.0
                emission.inputs["Color"].default_value = (value, value, value, 1.0)
                if source is not None and source.bl_idname not in {"ShaderNodeBsdfPrincipled", "ShaderNodeEmission"}:
                    warnings.append(f"材质 {material.name} 的复杂透明节点无法提取，已按不透明烘焙")
            for link in list(output.inputs["Surface"].links):
                links.remove(link)
            links.new(emission.outputs["Emission"], output.inputs["Surface"])
        bpy.ops.object.bake(type="EMIT", **arguments)
        color_pixels = array("f", [0.0]) * (resolution * resolution * 4)
        alpha_pixels = array("f", [0.0]) * (resolution * resolution * 4)
        color.pixels.foreach_get(color_pixels)
        alpha.pixels.foreach_get(alpha_pixels)
        for offset in range(0, len(color_pixels), 4):
            color_pixels[offset + 3] = max(0.0, min(1.0, float(alpha_pixels[offset])))
        color.pixels.foreach_set(color_pixels)
        color["halo_generated_texture"] = True
        color["halo_texture_id"] = texture_id
        color["halo_content_sha256"] = hashlib.sha256(color_pixels.tobytes()).hexdigest()
        with tempfile.TemporaryDirectory(prefix="halo_scene_mesh_bake_") as directory:
            bake_path = Path(directory) / "bake.png"
            color.filepath_raw = str(bake_path)
            color.file_format = "PNG"
            color.save()
            color.pack()
        color.filepath_raw = ""
        success = True
        return color, warnings
    finally:
        context.scene.render.engine = previous_engine
        _restore_selection(context, previous_selected, previous_active, previous_mode)
        if alpha.name in bpy.data.images and alpha.users == 0:
            bpy.data.images.remove(alpha)
        obj.data.materials.clear()
        for material in materials:
            if material.name in bpy.data.materials and material.users == 0:
                bpy.data.materials.remove(material)
        if not success and color.name in bpy.data.images and color.users == 0:
            bpy.data.images.remove(color)


def import_scene_mesh(
    context,
    source_obj,
    target_primitive,
    *,
    apply_modifiers: bool = True,
    coordinate_space: str = "TARGET_LOCAL",
    material_mode: str = "NONE",
    regenerate_bake_uv: bool = True,
    texture_resolution: int = 1024,
    bake_margin: int = 16,
    bake_mode: str = "AUTO",
) -> SceneMeshImportResult:
    """Convert a scene Mesh and attach the generated resources to a primitive."""

    if source_obj is None or source_obj.type != "MESH" or source_obj.get("halo_role"):
        raise ValueError("请选择当前场景中的普通 Mesh 对象")
    if (target_primitive is None or target_primitive.get("halo_role") != "primitive"
            or target_primitive.halo_node.primitive_type != "mesh"):
        raise ValueError("请先选择一个 Halo 原生 Mesh 图元")
    parent = target_primitive.parent
    if parent is None or parent.get("halo_role") not in {"group", "definition_root"}:
        raise ValueError("目标 Mesh 图元没有有效父级")
    from . import blender_scene
    pack_root = blender_scene.definition_pack_root(context.scene, target_primitive.get("halo_definition_id", ""))
    if not pack_root or not Path(pack_root).is_dir():
        from .resource_store import ensure_resources
        ensure_resources(context.scene)
        pack_root = blender_scene.definition_pack_root(context.scene, target_primitive.get("halo_definition_id", ""))
    if not pack_root or not Path(pack_root).is_dir():
        raise ValueError("无法建立资源目录，请先修复项目资源")

    definition_id = str(target_primitive.get("halo_definition_id", "minecraft:halo"))
    namespace = definition_id.split(":", 1)[0] if ":" in definition_id else "minecraft"
    stem = _safe_component(source_obj.name)
    depsgraph = context.evaluated_depsgraph_get()
    evaluated = source_obj.evaluated_get(depsgraph) if apply_modifiers else None
    evaluated_mesh = evaluated.to_mesh(preserve_all_data_layers=True, depsgraph=depsgraph) if evaluated else None
    mesh = (evaluated_mesh or source_obj.data).copy()
    temp_obj = bpy.data.objects.new(f"Halo OBJ Export {source_obj.name}", mesh)
    context.scene.collection.objects.link(temp_obj)
    generated_image = None
    warnings = []
    try:
        if str(coordinate_space).upper() == "TARGET_LOCAL":
            transform = parent.matrix_world.inverted_safe() @ source_obj.matrix_world
            mesh.transform(transform)
        material_mode = str(material_mode or "NONE").upper()
        texture_id = None
        if material_mode == "DIRECT":
            try:
                image, direct_warnings = _direct_image(temp_obj, mesh)
            except DirectUVUnsupported as exc:
                raise ValueError(f"无法直接导入材质：{exc}；请改用 Cycles 烘焙") from exc
            warnings.extend(direct_warnings)
            image_stem = Path(bpy.path.abspath(image.filepath)).stem if image.filepath else image.name
            texture_id, generated = _import_direct_texture(image, str(pack_root), namespace, image_stem or stem)
            if generated:
                generated_image = next(
                    image for image in bpy.data.images
                    if image.get("halo_generated_texture") and image.get("halo_texture_id") == texture_id
                )
        elif material_mode == "BAKE":
            if regenerate_bake_uv or mesh.uv_layers.active is None:
                bake_uv_name = _smart_uv(
                    context,
                    temp_obj,
                    max(0.001, float(bake_margin) / max(16, int(texture_resolution))),
                )
                if not regenerate_bake_uv:
                    warnings.append("源 Mesh 没有 UV，已自动生成 Smart UV")
            else:
                bake_uv_name = mesh.uv_layers.active.name
            texture_id, existing = _generated_texture_id(str(pack_root), namespace, f"{stem}_bake")
            if existing is not None:
                raise RuntimeError("内部错误：新烘焙纹理 ID 意外复用")
            generated_image, bake_warnings = _bake_texture(
                context, temp_obj, texture_resolution, bake_margin, bake_mode, texture_id, bake_uv_name,
            )
            warnings.extend(bake_warnings)
            mesh.uv_layers.active = mesh.uv_layers.get(bake_uv_name)
        elif material_mode != "NONE":
            raise ValueError(f"未知材质导入模式：{material_mode}")

        if mesh.uv_layers.active is None:
            _dummy_uv(mesh)
            warnings.append("源 Mesh 没有 UV；OBJ 已写入占位 UV，后续纹理需要重新导入模型")
        obj_text, triangle_count, skipped = obj_text_from_mesh(mesh, source_obj.name)
        with tempfile.TemporaryDirectory(prefix="halo_scene_mesh_obj_") as directory:
            source_path = Path(directory) / f"{stem}.obj"
            source_path.write_text(obj_text, encoding="utf-8", newline="\n")
            model_id, _destination = copy_obj_resource(
                source_path, str(pack_root), f"{namespace}:models/halo/{stem}.obj",
            )
        if skipped:
            warnings.append(f"已跳过 {skipped} 个退化三角形")
        return SceneMeshImportResult(
            model_id=model_id,
            texture_id=texture_id,
            triangle_count=triangle_count,
            skipped_degenerate=skipped,
            generated_texture=generated_image is not None,
            warnings=warnings,
        )
    except BaseException:
        if generated_image is not None and generated_image.name in bpy.data.images and generated_image.users == 0:
            bpy.data.images.remove(generated_image)
        raise
    finally:
        if temp_obj.name in bpy.data.objects:
            bpy.data.objects.remove(temp_obj, do_unlink=True)
        if mesh.users == 0:
            bpy.data.meshes.remove(mesh)
        if evaluated is not None:
            evaluated.to_mesh_clear()


__all__ = ["SceneMeshImportResult", "obj_text_from_mesh", "import_scene_mesh"]
